name: missyou
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^1.2.3
  pin_code_fields: ^2.3.0+3
  swipe_stack: ^1.0.0
  flutter_swiper: ^1.1.6
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  geolocator: ^5.3.0
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  firebase_storage: ^3.1.3
  path_provider:
  cached_network_image: ^2.0.0
  share: ^0.6.3+6
  firebase_messaging: ^6.0.13
  flutter_webview_plugin: ^0.3.11
  in_app_purchase: ^0.3.4
  rflutter_alert: ^1.0.3
  lottie: ^0.6.0

  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  agora_rtc_engine: 1.0.5
  permission_handler: ^3.0.0

  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "asset/Icon/icon.png" 
flutter:

  uses-material-design: true

  assets:
   - asset/auth/
   - asset/Icon/
   - asset/

  fonts:
    - family: Gilroy
      fonts:
        - asset: asset/fonts/Gilroy-Bold.ttf
    - family: vagnotie
      fonts:
        - asset: asset/fonts/vagnotie.ttf
    - family: miss
      fonts:
        - asset: asset/fonts/miss.otf
        
