name: missyou_admin
description: Flutter missyou admin panel

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.2
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
